# Generated by Django 5.2.1 on 2025-05-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classname",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.schedule"
            ),
        ),
    ]
