# Generated by Django 5.2.1 on 2025-05-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=100),
        ),
    ]
