# Generated by Django 5.2.1 on 2025-05-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('Biotechnology', 'Biotechnology'), ('Graphic Design', 'Graphic Design'), ('Data Science', 'Data Science'), ('Software Engineering', 'Software Engineering'), ('Cybersecurity', 'Cybersecurity'), ('Cloud Computing', 'Cloud Computing')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='student',
            table='inf',
        ),
    ]
