# Generated by Django 5.2.1 on 2025-05-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="schedule_id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major",
            field=models.CharField(max_length=100),
        ),
    ]
