# Generated by Django 5.2.1 on 2025-05-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_major_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='infor',
        ),
    ]
