# Generated by Django 5.2.1 on 2025-05-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("max_size", models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="student",
            table=None,
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "classname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.classname",
                        to_field="name",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                        to_field="student_id",
                    ),
                ),
            ],
        ),
    ]
