# Generated by Django 5.2.1 on 2025-05-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_classname_alter_student_major_alter_student_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclass",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
