# Generated by Django 5.2.1 on 2025-05-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_studentclass_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclass",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
